### PR TITLE
logstash6: upgrading http_client version

### PR DESCRIPTION
**Pull request by mschneider82**
for logstash 6.x

### CODE REVIEW

**Comment by dougburks** [comment]
Logstash 6.0.0 GA was officially released today:
https://www.elastic.co/blog/logstash-6-0-0-released

Is there an ETA for this PR to be merged?

Thanks!

**Comment by lucashenning** [comment]
Looks good. I'll look into it on the weekend. Thank you guys for your contributions.

**Comment by dougburks** [comment]
Anything we can do to assist with this?  Thanks!

**Comment by dougburks** [comment]
Hi @lucashenning ,

Anything we can do to help with this?

Thanks!

**Comment by lucashenning** [comment]
Just published the new version 0.5.5 compatible with logstash 6.0 

Thank you guys for your contributions! And my apologies for the delay, I haven't had much time to work on this. Glad it's updated now.

**Pull request merged**
