### PR TITLE
Handle Errors From HTTP Client

### PR DESCRIPTION
**Pull request by kalmas**
#16

### CODE REVIEW

**Comment by kalmas** [comment]
It's a local variable so it shouldn't hold state between calls to `filter()`. But I'll add a test to verify.

**Comment by kalmas** [comment]
Actually, I can't figure out an easy way to unit test that, I would need to be able to inject a mock client to simulate intermittent failure. 

That would require some plugin refactoring or some ruby-foo that I am lacking... probably both 😄

**Comment by gandalfb** [comment]
The sample spec helper from the logstash gem currently is not able to send events within a single instance.

Only way I found is to run a test with a real logstash within cli.
Maybe worth a try to verify what is not testable via unit test.

**Comment by kalmas** [comment]
Confirmed local variables are working as expected, and I added an explicit initialization for good measure.

**Comment by lucashenning** [comment]
Good job @kalmas & @gandalfb ! I appreciate your work and also learned something about variable state of logstash filter calls. Thanks :) Do you guys think this is ready to be merged and published to rubygems or does anyone of you wanna change something else right now?

**Comment by gandalfb** [comment]
```bash
Randomized with seed 14275
...............

Finished in 8.54 seconds (files took 4.26 seconds to load)
15 examples, 0 failures
```

looks good @lucashenning :smile: 
`nil` operation might be a "marker" to have a look at it again, when [this](https://github.com/elastic/logstash-devutils/issues/33) has been solved to "be sure" within unit testing.

**Pull request merged**
